title: Emily Woods

baseurl: ""
url: ""

permalink: "/blog/:title/"

# Build settings
markdown: kramdown
encoding: utf-8

exclude:
  - Gemfile
  - Gemfile.lock

future: true

highlighter: rouge

social:
  - icon: envelope
    title: email
    url: mailto:hello@emilywoods.me
  - icon: github
    title: github
    url: https://github.com/emilywoods
  - icon: twitter
    title: twitter
    url: https://www.twitter.com/sometimes_milo/

gems:
  - jekyll-feed
