baseurl: ""
url: ""

permalink: "/blog/:title/"

# Build settings
markdown: kramdown
encoding: utf-8

exclude:
  - Gemfile
  - Gemfile.lock

future: true

highlighter: rouge

social:
  - icon: assets/images/button/email.png
    title: email
    url: mailto:hello@emilywoods.me
  - icon: assets/images/button/github.png
    title: github
    url: https://github.com/emilywoods
  - icon: assets/images/button/insta.png
    title: instagram
    url: https://www.instagram.com/emilym.woods/
