baseurl: ""
url: ""

permalink: "/blog/:title/"

# Build settings
markdown: kramdown
encoding: utf-8

exclude:
  - Gemfile
  - Gemfile.lock

future: true

highlighter: rouge

social:
  - icon: envelope-o
    title: email
    url: mailto:hello@emilywoods.me
  - icon: github
    title: github
    url: https://github.com/emilywoods
  - icon: linkedin
    title: linkedin
    url: https://uk.linkedin.com/in/emily-woods-38494083
